import type { NextPage } from 'next';
import Head from 'next/head';
import CatCard, { ICatCard } from '../components/cards/cat/CatCard';
import MainLayout from '../components/layouts/main/MainLayout';
import BaseTemplate from '../components/templates/base/BaseTemplate';
import styles from '../styles/Home.module.scss';
const base: ICatCard = {
  tag: 'Felines',
  title: `What's new in Cats`,
  body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi perferendis molestiae non nemo doloribus. Doloremque, nihil! At ea atque quidem!',
  author: 'Alex',
  time: '2h ago',
};
const Home: NextPage = () => {
  return (
    <MainLayout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <BaseTemplate sampleTextProp="test"></BaseTemplate>
          <CatCard {...base}></CatCard>
          Index Page
        </main>
      </div>
    </MainLayout>
  );
};

export default Home;
